server:
  port: 9999
spring:
  application:
    name: SCRIBBLE-PAD-BE
  datasource:
    url: jdbc:mysql://localhost:3306/scribble_pad
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/scribble-pad
          jwk-set-uri: http://localhost:8080/realms/scribble-pad/protocol/openid-connect/certs
#logging:
#  level:
#    '[org.springframework.jdbc.core]': TRACE 